import { ConfigurableAbstract } from "../node_modules/mudde-core/src/Mudde/Core/ConfigurableAbstract";
import HandlerInterface from "../node_modules/mudde-core/src/Mudde/Core/HandlerInterface";
import NodeCore from "../node_modules/mudde-core/src/Mudde/Core/NodeCore";
import Form from "./Form";
export abstract class InputAbstract extends ConfigurableAbstract {
    private __type;
    private _id;
    private _label;
    private _help;
    private _placeholder;
    private _panel;
    private _unique;
    private _input;
    private _autofocus;
    private _hidden;
    private _require;
    private _multilingual;
    private _handler?;
    private _handlerCurrent?;
    private _form?;
    private _coreIds;
    constructor(form: Form);
    abstract coreHTMLInput(id: string, name: string, language: string): NodeCore;
    protected preCoreHTMLInput(): NodeCore | null;
    protected preHTMLInput(): NodeCore | null;
    protected postCoreHTMLInput(): NodeCore | null;
    protected postHTMLInput(): NodeCore | null;
    protected javascript(): string;
    protected canBeMultilingual(): boolean;
    getDefaultConfig(): {
        _type: string;
        id: string;
        input: boolean;
        label: string;
        help: string;
        unique: boolean;
        validations: any[];
        placeholder: string;
        panel: any;
        autofocus: boolean;
        require: boolean;
        hidden: boolean;
        multilingual: boolean;
        builders: any[];
    };
    private configureBuilders;
    private configureValidations;
    render(): NodeCore;
    get isMultilingual(): boolean;
    set id(value: string);
    get id(): string;
    set input(value: boolean);
    get input(): boolean;
    set _type(value: string);
    get _type(): string;
    set label(value: string);
    get label(): string;
    set help(value: string);
    get help(): string;
    set unique(value: boolean);
    get unique(): boolean;
    set handler(value: HandlerInterface);
    get handler(): HandlerInterface;
    set autofocus(value: boolean);
    get autofocus(): boolean;
    set hidden(value: boolean);
    get hidden(): boolean;
    set require(value: boolean);
    get require(): boolean;
    set multilingual(value: boolean);
    get multilingual(): boolean;
    set form(value: Form);
    get form(): Form;
    set placeholder(value: string);
    get placeholder(): string;
    set panel(value: string);
    get panel(): string;
    get coreIds(): NodeCore[];
    set coreIds(value: NodeCore[]);
}
